### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by BJNFNE** [pulkomandy/vtech-discotool#2]
Is there something being planned to add to the project, do you Need some help?

**Comment by pulkomandy** [comment]
There are many plans but no time to work on them :(

- Replace Haiku specific serial port access with something standard (termios?) so people on other OS can use this as well
- Modify the firmware on the disco cart to use a more compact way to transfer the data (currently it uses hexadecimal if I remember correctly, so half the bandwidth of the serial port is wasted)
- Modify the firmware to compare the data blocks with what's already in the flash, if it matches, do not erase and rewrite the same thing. Maybe optionally do the same in the software side as well (so we can save the serial transfer time in addition to the flash erase/write time).

These changes would make the flashing a lot faster and more comfortable to use

**Comment by BJNFNE** [comment]
@pulkomandy Is there maybe an way also to contact you on Discord for faster communation? I would like to help out as much as i can in the project.

**Comment by BJNFNE** [comment]
Thank you, since we continue our conversation on Discord i close this as Done.
